# Generated by Django 3.2.6 on 2023-09-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist', models.CharField(max_length=255)),
                ('clinic', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('treatment', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('orthodontic_treatment_in_past', models.CharField(max_length=255)),
                ('additional_information', models.TextField()),
                ('additional_image', models.ImageField(upload_to='additional_images/')),
                ('upper_jaw_image', models.ImageField(upload_to='upper_jaw_images/')),
            ],
        ),
    ]
