# Generated by Django 3.2.6 on 2023-09-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230903_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
